export const STATUS_LABELS: Record<string, string> = {
  PREORDER_SUBMITTED: 'Pre-Order Submitted',
  AWAITING_WAREHOUSE_RECEIPT: 'Awaiting Warehouse Receipt',
  WAREHOUSE_RECEIVED: 'Received at Warehouse',
  WAREHOUSE_VERIFIED_PRICED: 'Verified & Priced',
  DISPATCHED_TO_ORIGIN_AIRPORT: 'Dispatched to Airport',
  AT_ORIGIN_AIRPORT: 'At Origin Airport',
  BOARDED_ON_FLIGHT: 'Boarded on Flight',
  FLIGHT_DEPARTED: 'Flight Departed',
  FLIGHT_LANDED_LAGOS: 'Landed in Lagos',
  DISPATCHED_TO_ORIGIN_PORT: 'Dispatched to Port',
  AT_ORIGIN_PORT: 'At Origin Port',
  LOADED_ON_VESSEL: 'Loaded on Vessel',
  VESSEL_DEPARTED: 'Vessel Departed',
  VESSEL_ARRIVED_LAGOS_PORT: 'Arrived at Lagos Port',
  CUSTOMS_CLEARED_LAGOS: 'Customs Cleared',
  IN_TRANSIT_TO_LAGOS_OFFICE: 'In Transit to Office',
  READY_FOR_PICKUP: 'Ready for Pickup',
  PICKED_UP_COMPLETED: 'Delivered',
  ON_HOLD: 'On Hold',
  CANCELLED: 'Cancelled',
  RESTRICTED_ITEM_REJECTED: 'Restricted Item – Rejected',
  RESTRICTED_ITEM_OVERRIDE_APPROVED: 'Restricted Item – Override Approved',
}
