export const STATUS_LABELS: Record<string, string> = {
  PREORDER_SUBMITTED: 'Pre-Order Submitted',
  AWAITING_WAREHOUSE_RECEIPT: 'Awaiting Warehouse Receipt',
  WAREHOUSE_RECEIVED: 'Received at Warehouse',
  CLAIM_APPROVED_PENDING_BULK_PROCESSING: 'Claim Approved — Pending Bulk Processing',
  WAREHOUSE_VERIFIED_PRICED: 'Verified & Priced',
  DISPATCHED_TO_ORIGIN_AIRPORT: 'Dispatched to Airport',
  AT_ORIGIN_AIRPORT: 'At Origin Airport',
  BOARDED_ON_FLIGHT: 'Boarded on Flight',
  FLIGHT_DEPARTED: 'Flight Departed',
  FLIGHT_LANDED_LAGOS: 'Landed in Lagos',
  DISPATCHED_TO_ORIGIN_PORT: 'Dispatched to Port',
  AT_ORIGIN_PORT: 'At Origin Port',
  LOADED_ON_VESSEL: 'Loaded on Vessel',
  VESSEL_DEPARTED: 'Vessel Departed',
  VESSEL_ARRIVED_LAGOS_PORT: 'Arrived at Lagos Port',
  CUSTOMS_CLEARED_LAGOS: 'Customs Cleared',
  IN_TRANSIT_TO_LAGOS_OFFICE: 'In Transit to Office',
  IN_EXTRA_TRUCK_MOVEMENT_LAGOS: 'In Extra Truck Movement (Lagos)',
  READY_FOR_PICKUP: 'Ready for Pickup',
  PICKED_UP_COMPLETED: 'Delivered',
  LOCAL_COURIER_ASSIGNED: 'Local Courier Assigned',
  IN_TRANSIT_TO_DESTINATION_CITY: 'In Transit to Destination City',
  OUT_FOR_DELIVERY_DESTINATION_CITY: 'Out for Delivery',
  DELIVERED_TO_RECIPIENT: 'Delivered to Recipient',
  ON_HOLD: 'On Hold',
  CANCELLED: 'Cancelled',
  RESTRICTED_ITEM_REJECTED: 'Restricted Item – Rejected',
  RESTRICTED_ITEM_OVERRIDE_APPROVED: 'Restricted Item – Override Approved',
}
