import { createHmac, randomBytes, timingSafeEqual } from 'crypto'
import { env } from '../config/env'

/**
 * Single-use MFA recovery codes.
 *
 * Codes are randomly generated by the server (high entropy) and displayed
 * to the user exactly once at enrollment. We store HMAC-SHA256 hashes (keyed
 * with the existing ENCRYPTION_KEY) so a DB leak doesn't yield usable codes.
 *
 * HMAC is appropriate here (not bcrypt) because the codes are generated with
 * full entropy by us — no offline guessing risk. HMAC is also fast enough that
 * iterating over the user's remaining codes at login is cheap.
 */

const CODE_COUNT = 10
// 5 bytes ≈ 8 base32 chars per group; two groups separated by hyphen.
const GROUP_BYTES = 5
const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'

function group(): string {
  const bytes = randomBytes(GROUP_BYTES)
  let out = ''
  for (let i = 0; i < bytes.length; i++) {
    // 8 bits → take 5-bit nibbles; simpler approach: per-byte mod with bias-free
    // selection isn't required here because we discard 3 bits per byte and the
    // remaining entropy (40 bits → 25 chars) is more than enough for one-time codes.
    out += ALPHABET[bytes[i] & 0x1f]
  }
  return out
}

export function generatePlaintextRecoveryCodes(count = CODE_COUNT): string[] {
  return Array.from({ length: count }, () => `${group()}-${group()}`)
}

function normalize(code: string): string {
  return code.replace(/\s+/g, '').replace(/-/g, '').toUpperCase()
}

export function hashRecoveryCode(code: string): string {
  return createHmac('sha256', env.ENCRYPTION_KEY).update(normalize(code)).digest('hex')
}

export function hashRecoveryCodes(codes: string[]): string[] {
  return codes.map(hashRecoveryCode)
}

/**
 * Verifies a candidate code against the stored hash list.
 * Returns the updated list with the consumed hash removed, or null if no match.
 */
export function consumeRecoveryCode(
  candidate: string,
  storedHashes: string[],
): { updated: string[] } | null {
  if (typeof candidate !== 'string' || candidate.length === 0) return null
  const candidateHash = hashRecoveryCode(candidate)
  const candidateBuf = Buffer.from(candidateHash, 'hex')

  for (let i = 0; i < storedHashes.length; i++) {
    const stored = Buffer.from(storedHashes[i], 'hex')
    if (stored.length !== candidateBuf.length) continue
    if (timingSafeEqual(stored, candidateBuf)) {
      const updated = [...storedHashes.slice(0, i), ...storedHashes.slice(i + 1)]
      return { updated }
    }
  }
  return null
}
